import { invoke } from '@tauri-apps/api/core';

// Types (these will be auto-generated by tauri-specta eventually)
export interface CreateAccountInput {
  name: string;
  provider_id: string;
  cookies: Record<string, string>;
  api_user?: string;
  auto_checkin_enabled?: boolean;
  auto_checkin_hour?: number;
  auto_checkin_minute?: number;
}

export interface UpdateAccountInput {
  account_id: string;
  name?: string;
  cookies?: Record<string, string>;
  api_user?: string;
  auto_checkin_enabled?: boolean;
  auto_checkin_hour?: number;
  auto_checkin_minute?: number;
}

export interface Account {
  id: string;
  name: string;
  provider_id: string;
  provider_name: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  auto_checkin_enabled: boolean;
  auto_checkin_hour: number;
  auto_checkin_minute: number;
  last_check_in?: string;
  current_balance?: number;
  total_consumed?: number;
  total_income?: number;
  last_balance_check_at?: string;
}

export interface AccountDetail extends Account {
  cookies: Record<string, string>;
  api_user?: string;
  balance?: number;
}

// Account Commands
export const accountCommands = {
  getAll: (enabledOnly: boolean = false) =>
    invoke<Account[]>('get_all_accounts', { enabledOnly }),

  getDetail: (accountId: string) =>
    invoke<AccountDetail>('get_account_detail', { accountId }),

  create: (input: CreateAccountInput) =>
    invoke<string>('create_account', { input }),

  update: (input: UpdateAccountInput) =>
    invoke('update_account', { input }),

  delete: (accountId: string) =>
    invoke('delete_account', { accountId }),

  toggle: (accountId: string, enabled: boolean) =>
    invoke('toggle_account', { accountId, enabled }),

  importFromJson: (jsonData: string) =>
    invoke<string>('import_account_from_json', { jsonData }),

  importBatch: (jsonData: string) =>
    invoke<string[]>('import_accounts_batch', { jsonData }),

  exportToJson: (accountIds: string[], includeCredentials: boolean) =>
    invoke<string>('export_accounts_to_json', { 
      accountIds, 
      includeCredentials 
    }),
};

// Check-in Commands (placeholder for future implementation)
export const checkInCommands = {
  execute: (accountId: string) =>
    invoke('execute_check_in', { accountId }),

  executeBatch: (accountIds: string[]) =>
    invoke('execute_batch_check_in', { accountIds }),

  getHistory: (accountId: string, page: number, pageSize: number) =>
    invoke('get_check_in_history', { accountId, page, pageSize }),
};
