import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { invoke } from '@tauri-apps/api/core';

// Types (these will be auto-generated by Tauri + Specta, but we define them here for development)
export interface CheckInStreakDto {
  account_id: string;
  account_name: string;
  provider_id: string;
  provider_name: string;
  current_streak: number;
  longest_streak: number;
  total_check_in_days: number;
  last_check_in_date: string | null; // YYYY-MM-DD
}

export interface CheckInDayDto {
  date: string; // YYYY-MM-DD
  is_checked_in: boolean;
  income_increment: number | null;
  current_balance: number;
  total_consumed: number;
  total_income: number;
}

export interface MonthStatsDto {
  total_days: number;
  checked_in_days: number;
  check_in_rate: number; // 0.0 - 100.0
  total_income_increment: number;
}

export interface CheckInCalendarDto {
  account_id: string;
  year: number;
  month: number;
  days: CheckInDayDto[];
  month_stats: MonthStatsDto;
}

export interface TrendDataPoint {
  date: string;
  total_income: number;
  income_increment: number;
  current_balance: number;
  is_checked_in: boolean;
}

export interface CheckInTrendDto {
  account_id: string;
  start_date: string;
  end_date: string;
  data_points: TrendDataPoint[];
}

// Hook: Get streak for a single account
export function useCheckInStreak(accountId: string, enabled = true) {
  return useQuery({
    queryKey: ['checkInStreak', accountId],
    queryFn: () => invoke<CheckInStreakDto>('get_check_in_streak', { accountId }),
    enabled: enabled && !!accountId,
    staleTime: 60000, // 1 minute
  });
}

// Hook: Get all streaks
export function useAllCheckInStreaks() {
  return useQuery({
    queryKey: ['checkInStreaks'],
    queryFn: () => invoke<CheckInStreakDto[]>('get_all_check_in_streaks'),
    staleTime: 60000, // 1 minute
  });
}

// Hook: Get calendar for a specific month
export function useCheckInCalendar(
  accountId: string,
  year: number,
  month: number,
  enabled = true
) {
  return useQuery({
    queryKey: ['checkInCalendar', accountId, year, month],
    queryFn: () =>
      invoke<CheckInCalendarDto>('get_check_in_calendar', {
        accountId,
        year,
        month,
      }),
    enabled: enabled && !!accountId,
    staleTime: 60000, // 1 minute
  });
}

// Hook: Get trend data (last N days)
export function useCheckInTrend(accountId: string, days: number = 30, enabled = true) {
  return useQuery({
    queryKey: ['checkInTrend', accountId, days],
    queryFn: () =>
      invoke<CheckInTrendDto>('get_check_in_trend', {
        accountId,
        days,
      }),
    enabled: enabled && !!accountId,
    staleTime: 60000, // 1 minute
  });
}

// Hook: Get day detail
export function useCheckInDayDetail(accountId: string, date: string, enabled = true) {
  return useQuery({
    queryKey: ['checkInDayDetail', accountId, date],
    queryFn: () =>
      invoke<CheckInDayDto>('get_check_in_day_detail', {
        accountId,
        date,
      }),
    enabled: enabled && !!accountId && !!date,
  });
}

// Hook: Recalculate all streaks (mutation)
export function useRecalculateStreaks() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: () => invoke('recalculate_check_in_streaks'),
    onSuccess: () => {
      // Invalidate all streak-related queries
      queryClient.invalidateQueries({ queryKey: ['checkInStreaks'] });
      queryClient.invalidateQueries({ queryKey: ['checkInStreak'] });
      queryClient.invalidateQueries({ queryKey: ['checkInCalendar'] });
      queryClient.invalidateQueries({ queryKey: ['checkInTrend'] });
    },
  });
}
